//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce.siproe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://siproe.com/")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int TarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tarjeta {
            get {
                return this.TarjetaField;
            }
            set {
                if ((this.TarjetaField.Equals(value) != true)) {
                    this.TarjetaField = value;
                    this.RaisePropertyChanged("Tarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://siproe.com/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://siproe.com/")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siproe.com/", ConfigurationName="siproe.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/iniciarSesion", ReplyAction="*")]
        e_commerce.siproe.iniciarSesionResponse iniciarSesion(e_commerce.siproe.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/iniciarSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.iniciarSesionResponse> iniciarSesionAsync(e_commerce.siproe.iniciarSesionRequest request);
        
        // CODEGEN: Generating message contract since element name selectAllProveedoresResult from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectAllProveedores", ReplyAction="*")]
        e_commerce.siproe.selectAllProveedoresResponse selectAllProveedores(e_commerce.siproe.selectAllProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectAllProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.selectAllProveedoresResponse> selectAllProveedoresAsync(e_commerce.siproe.selectAllProveedoresRequest request);
        
        // CODEGEN: Generating message contract since element name selectProveedorResult from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectProveedor", ReplyAction="*")]
        e_commerce.siproe.selectProveedorResponse selectProveedor(e_commerce.siproe.selectProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.selectProveedorResponse> selectProveedorAsync(e_commerce.siproe.selectProveedorRequest request);
        
        // CODEGEN: Generating message contract since element name proveedor from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/updateProveedor", ReplyAction="*")]
        e_commerce.siproe.updateProveedorResponse updateProveedor(e_commerce.siproe.updateProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/updateProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.updateProveedorResponse> updateProveedorAsync(e_commerce.siproe.updateProveedorRequest request);
        
        // CODEGEN: Generating message contract since element name proveedor from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/insertProveedor", ReplyAction="*")]
        e_commerce.siproe.insertProveedorResponse insertProveedor(e_commerce.siproe.insertProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/insertProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.insertProveedorResponse> insertProveedorAsync(e_commerce.siproe.insertProveedorRequest request);
        
        // CODEGEN: Generating message contract since element name selectAllProductosResult from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectAllProductos", ReplyAction="*")]
        e_commerce.siproe.selectAllProductosResponse selectAllProductos(e_commerce.siproe.selectAllProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectAllProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.selectAllProductosResponse> selectAllProductosAsync(e_commerce.siproe.selectAllProductosRequest request);
        
        // CODEGEN: Generating message contract since element name nombrePro from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectProducto", ReplyAction="*")]
        e_commerce.siproe.selectProductoResponse selectProducto(e_commerce.siproe.selectProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/selectProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.selectProductoResponse> selectProductoAsync(e_commerce.siproe.selectProductoRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/updateUnProducto", ReplyAction="*")]
        e_commerce.siproe.updateUnProductoResponse updateUnProducto(e_commerce.siproe.updateUnProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/updateUnProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.updateUnProductoResponse> updateUnProductoAsync(e_commerce.siproe.updateUnProductoRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/addProducto", ReplyAction="*")]
        e_commerce.siproe.addProductoResponse addProducto(e_commerce.siproe.addProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/addProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.addProductoResponse> addProductoAsync(e_commerce.siproe.addProductoRequest request);
        
        // CODEGEN: Generating message contract since element name getCategoriaResult from namespace http://siproe.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/getCategoria", ReplyAction="*")]
        e_commerce.siproe.getCategoriaResponse getCategoria(e_commerce.siproe.getCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siproe.com/getCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<e_commerce.siproe.getCategoriaResponse> getCategoriaAsync(e_commerce.siproe.getCategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iniciarSesion", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.iniciarSesionRequestBody Body;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(e_commerce.siproe.iniciarSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class iniciarSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        public iniciarSesionRequestBody() {
        }
        
        public iniciarSesionRequestBody(string usuario, string contrasenia) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="iniciarSesionResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.iniciarSesionResponseBody Body;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(e_commerce.siproe.iniciarSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class iniciarSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Proveedor iniciarSesionResult;
        
        public iniciarSesionResponseBody() {
        }
        
        public iniciarSesionResponseBody(e_commerce.siproe.Proveedor iniciarSesionResult) {
            this.iniciarSesionResult = iniciarSesionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllProveedores", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectAllProveedoresRequestBody Body;
        
        public selectAllProveedoresRequest() {
        }
        
        public selectAllProveedoresRequest(e_commerce.siproe.selectAllProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectAllProveedoresRequestBody {
        
        public selectAllProveedoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllProveedoresResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectAllProveedoresResponseBody Body;
        
        public selectAllProveedoresResponse() {
        }
        
        public selectAllProveedoresResponse(e_commerce.siproe.selectAllProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectAllProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<e_commerce.siproe.Proveedor> selectAllProveedoresResult;
        
        public selectAllProveedoresResponseBody() {
        }
        
        public selectAllProveedoresResponseBody(System.Collections.Generic.List<e_commerce.siproe.Proveedor> selectAllProveedoresResult) {
            this.selectAllProveedoresResult = selectAllProveedoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectProveedor", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectProveedorRequestBody Body;
        
        public selectProveedorRequest() {
        }
        
        public selectProveedorRequest(e_commerce.siproe.selectProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public selectProveedorRequestBody() {
        }
        
        public selectProveedorRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectProveedorResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectProveedorResponseBody Body;
        
        public selectProveedorResponse() {
        }
        
        public selectProveedorResponse(e_commerce.siproe.selectProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Proveedor selectProveedorResult;
        
        public selectProveedorResponseBody() {
        }
        
        public selectProveedorResponseBody(e_commerce.siproe.Proveedor selectProveedorResult) {
            this.selectProveedorResult = selectProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProveedor", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.updateProveedorRequestBody Body;
        
        public updateProveedorRequest() {
        }
        
        public updateProveedorRequest(e_commerce.siproe.updateProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class updateProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Proveedor proveedor;
        
        public updateProveedorRequestBody() {
        }
        
        public updateProveedorRequestBody(e_commerce.siproe.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProveedorResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.updateProveedorResponseBody Body;
        
        public updateProveedorResponse() {
        }
        
        public updateProveedorResponse(e_commerce.siproe.updateProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateProveedorResponseBody {
        
        public updateProveedorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertProveedor", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.insertProveedorRequestBody Body;
        
        public insertProveedorRequest() {
        }
        
        public insertProveedorRequest(e_commerce.siproe.insertProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class insertProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Proveedor proveedor;
        
        public insertProveedorRequestBody() {
        }
        
        public insertProveedorRequestBody(e_commerce.siproe.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertProveedorResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.insertProveedorResponseBody Body;
        
        public insertProveedorResponse() {
        }
        
        public insertProveedorResponse(e_commerce.siproe.insertProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertProveedorResponseBody {
        
        public insertProveedorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllProductos", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectAllProductosRequestBody Body;
        
        public selectAllProductosRequest() {
        }
        
        public selectAllProductosRequest(e_commerce.siproe.selectAllProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectAllProductosRequestBody {
        
        public selectAllProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllProductosResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectAllProductosResponseBody Body;
        
        public selectAllProductosResponse() {
        }
        
        public selectAllProductosResponse(e_commerce.siproe.selectAllProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectAllProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<e_commerce.siproe.Producto> selectAllProductosResult;
        
        public selectAllProductosResponseBody() {
        }
        
        public selectAllProductosResponseBody(System.Collections.Generic.List<e_commerce.siproe.Producto> selectAllProductosResult) {
            this.selectAllProductosResult = selectAllProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectProducto", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectProductoRequestBody Body;
        
        public selectProductoRequest() {
        }
        
        public selectProductoRequest(e_commerce.siproe.selectProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombrePro;
        
        public selectProductoRequestBody() {
        }
        
        public selectProductoRequestBody(string nombrePro) {
            this.nombrePro = nombrePro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectProductoResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.selectProductoResponseBody Body;
        
        public selectProductoResponse() {
        }
        
        public selectProductoResponse(e_commerce.siproe.selectProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class selectProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Producto selectProductoResult;
        
        public selectProductoResponseBody() {
        }
        
        public selectProductoResponseBody(e_commerce.siproe.Producto selectProductoResult) {
            this.selectProductoResult = selectProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUnProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUnProducto", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.updateUnProductoRequestBody Body;
        
        public updateUnProductoRequest() {
        }
        
        public updateUnProductoRequest(e_commerce.siproe.updateUnProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class updateUnProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Producto producto;
        
        public updateUnProductoRequestBody() {
        }
        
        public updateUnProductoRequestBody(e_commerce.siproe.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUnProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUnProductoResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.updateUnProductoResponseBody Body;
        
        public updateUnProductoResponse() {
        }
        
        public updateUnProductoResponse(e_commerce.siproe.updateUnProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateUnProductoResponseBody {
        
        public updateUnProductoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addProducto", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.addProductoRequestBody Body;
        
        public addProductoRequest() {
        }
        
        public addProductoRequest(e_commerce.siproe.addProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class addProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_commerce.siproe.Producto producto;
        
        public addProductoRequestBody() {
        }
        
        public addProductoRequestBody(e_commerce.siproe.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addProductoResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.addProductoResponseBody Body;
        
        public addProductoResponse() {
        }
        
        public addProductoResponse(e_commerce.siproe.addProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addProductoResponseBody {
        
        public addProductoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategoria", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.getCategoriaRequestBody Body;
        
        public getCategoriaRequest() {
        }
        
        public getCategoriaRequest(e_commerce.siproe.getCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCategoriaRequestBody {
        
        public getCategoriaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategoriaResponse", Namespace="http://siproe.com/", Order=0)]
        public e_commerce.siproe.getCategoriaResponseBody Body;
        
        public getCategoriaResponse() {
        }
        
        public getCategoriaResponse(e_commerce.siproe.getCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://siproe.com/")]
    public partial class getCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<e_commerce.siproe.Categoria> getCategoriaResult;
        
        public getCategoriaResponseBody() {
        }
        
        public getCategoriaResponseBody(System.Collections.Generic.List<e_commerce.siproe.Categoria> getCategoriaResult) {
            this.getCategoriaResult = getCategoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : e_commerce.siproe.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<e_commerce.siproe.ServicioWebSoap>, e_commerce.siproe.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.iniciarSesionResponse e_commerce.siproe.ServicioWebSoap.iniciarSesion(e_commerce.siproe.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public e_commerce.siproe.Proveedor iniciarSesion(string usuario, string contrasenia) {
            e_commerce.siproe.iniciarSesionRequest inValue = new e_commerce.siproe.iniciarSesionRequest();
            inValue.Body = new e_commerce.siproe.iniciarSesionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            e_commerce.siproe.iniciarSesionResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).iniciarSesion(inValue);
            return retVal.Body.iniciarSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.iniciarSesionResponse> e_commerce.siproe.ServicioWebSoap.iniciarSesionAsync(e_commerce.siproe.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.iniciarSesionResponse> iniciarSesionAsync(string usuario, string contrasenia) {
            e_commerce.siproe.iniciarSesionRequest inValue = new e_commerce.siproe.iniciarSesionRequest();
            inValue.Body = new e_commerce.siproe.iniciarSesionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).iniciarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.selectAllProveedoresResponse e_commerce.siproe.ServicioWebSoap.selectAllProveedores(e_commerce.siproe.selectAllProveedoresRequest request) {
            return base.Channel.selectAllProveedores(request);
        }
        
        public System.Collections.Generic.List<e_commerce.siproe.Proveedor> selectAllProveedores() {
            e_commerce.siproe.selectAllProveedoresRequest inValue = new e_commerce.siproe.selectAllProveedoresRequest();
            inValue.Body = new e_commerce.siproe.selectAllProveedoresRequestBody();
            e_commerce.siproe.selectAllProveedoresResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).selectAllProveedores(inValue);
            return retVal.Body.selectAllProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.selectAllProveedoresResponse> e_commerce.siproe.ServicioWebSoap.selectAllProveedoresAsync(e_commerce.siproe.selectAllProveedoresRequest request) {
            return base.Channel.selectAllProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.selectAllProveedoresResponse> selectAllProveedoresAsync() {
            e_commerce.siproe.selectAllProveedoresRequest inValue = new e_commerce.siproe.selectAllProveedoresRequest();
            inValue.Body = new e_commerce.siproe.selectAllProveedoresRequestBody();
            return ((e_commerce.siproe.ServicioWebSoap)(this)).selectAllProveedoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.selectProveedorResponse e_commerce.siproe.ServicioWebSoap.selectProveedor(e_commerce.siproe.selectProveedorRequest request) {
            return base.Channel.selectProveedor(request);
        }
        
        public e_commerce.siproe.Proveedor selectProveedor(int id) {
            e_commerce.siproe.selectProveedorRequest inValue = new e_commerce.siproe.selectProveedorRequest();
            inValue.Body = new e_commerce.siproe.selectProveedorRequestBody();
            inValue.Body.id = id;
            e_commerce.siproe.selectProveedorResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).selectProveedor(inValue);
            return retVal.Body.selectProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.selectProveedorResponse> e_commerce.siproe.ServicioWebSoap.selectProveedorAsync(e_commerce.siproe.selectProveedorRequest request) {
            return base.Channel.selectProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.selectProveedorResponse> selectProveedorAsync(int id) {
            e_commerce.siproe.selectProveedorRequest inValue = new e_commerce.siproe.selectProveedorRequest();
            inValue.Body = new e_commerce.siproe.selectProveedorRequestBody();
            inValue.Body.id = id;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).selectProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.updateProveedorResponse e_commerce.siproe.ServicioWebSoap.updateProveedor(e_commerce.siproe.updateProveedorRequest request) {
            return base.Channel.updateProveedor(request);
        }
        
        public void updateProveedor(e_commerce.siproe.Proveedor proveedor) {
            e_commerce.siproe.updateProveedorRequest inValue = new e_commerce.siproe.updateProveedorRequest();
            inValue.Body = new e_commerce.siproe.updateProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            e_commerce.siproe.updateProveedorResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).updateProveedor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.updateProveedorResponse> e_commerce.siproe.ServicioWebSoap.updateProveedorAsync(e_commerce.siproe.updateProveedorRequest request) {
            return base.Channel.updateProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.updateProveedorResponse> updateProveedorAsync(e_commerce.siproe.Proveedor proveedor) {
            e_commerce.siproe.updateProveedorRequest inValue = new e_commerce.siproe.updateProveedorRequest();
            inValue.Body = new e_commerce.siproe.updateProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).updateProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.insertProveedorResponse e_commerce.siproe.ServicioWebSoap.insertProveedor(e_commerce.siproe.insertProveedorRequest request) {
            return base.Channel.insertProveedor(request);
        }
        
        public void insertProveedor(e_commerce.siproe.Proveedor proveedor) {
            e_commerce.siproe.insertProveedorRequest inValue = new e_commerce.siproe.insertProveedorRequest();
            inValue.Body = new e_commerce.siproe.insertProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            e_commerce.siproe.insertProveedorResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).insertProveedor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.insertProveedorResponse> e_commerce.siproe.ServicioWebSoap.insertProveedorAsync(e_commerce.siproe.insertProveedorRequest request) {
            return base.Channel.insertProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.insertProveedorResponse> insertProveedorAsync(e_commerce.siproe.Proveedor proveedor) {
            e_commerce.siproe.insertProveedorRequest inValue = new e_commerce.siproe.insertProveedorRequest();
            inValue.Body = new e_commerce.siproe.insertProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).insertProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.selectAllProductosResponse e_commerce.siproe.ServicioWebSoap.selectAllProductos(e_commerce.siproe.selectAllProductosRequest request) {
            return base.Channel.selectAllProductos(request);
        }
        
        public System.Collections.Generic.List<e_commerce.siproe.Producto> selectAllProductos() {
            e_commerce.siproe.selectAllProductosRequest inValue = new e_commerce.siproe.selectAllProductosRequest();
            inValue.Body = new e_commerce.siproe.selectAllProductosRequestBody();
            e_commerce.siproe.selectAllProductosResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).selectAllProductos(inValue);
            return retVal.Body.selectAllProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.selectAllProductosResponse> e_commerce.siproe.ServicioWebSoap.selectAllProductosAsync(e_commerce.siproe.selectAllProductosRequest request) {
            return base.Channel.selectAllProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.selectAllProductosResponse> selectAllProductosAsync() {
            e_commerce.siproe.selectAllProductosRequest inValue = new e_commerce.siproe.selectAllProductosRequest();
            inValue.Body = new e_commerce.siproe.selectAllProductosRequestBody();
            return ((e_commerce.siproe.ServicioWebSoap)(this)).selectAllProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.selectProductoResponse e_commerce.siproe.ServicioWebSoap.selectProducto(e_commerce.siproe.selectProductoRequest request) {
            return base.Channel.selectProducto(request);
        }
        
        public e_commerce.siproe.Producto selectProducto(string nombrePro) {
            e_commerce.siproe.selectProductoRequest inValue = new e_commerce.siproe.selectProductoRequest();
            inValue.Body = new e_commerce.siproe.selectProductoRequestBody();
            inValue.Body.nombrePro = nombrePro;
            e_commerce.siproe.selectProductoResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).selectProducto(inValue);
            return retVal.Body.selectProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.selectProductoResponse> e_commerce.siproe.ServicioWebSoap.selectProductoAsync(e_commerce.siproe.selectProductoRequest request) {
            return base.Channel.selectProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.selectProductoResponse> selectProductoAsync(string nombrePro) {
            e_commerce.siproe.selectProductoRequest inValue = new e_commerce.siproe.selectProductoRequest();
            inValue.Body = new e_commerce.siproe.selectProductoRequestBody();
            inValue.Body.nombrePro = nombrePro;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).selectProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.updateUnProductoResponse e_commerce.siproe.ServicioWebSoap.updateUnProducto(e_commerce.siproe.updateUnProductoRequest request) {
            return base.Channel.updateUnProducto(request);
        }
        
        public void updateUnProducto(e_commerce.siproe.Producto producto) {
            e_commerce.siproe.updateUnProductoRequest inValue = new e_commerce.siproe.updateUnProductoRequest();
            inValue.Body = new e_commerce.siproe.updateUnProductoRequestBody();
            inValue.Body.producto = producto;
            e_commerce.siproe.updateUnProductoResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).updateUnProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.updateUnProductoResponse> e_commerce.siproe.ServicioWebSoap.updateUnProductoAsync(e_commerce.siproe.updateUnProductoRequest request) {
            return base.Channel.updateUnProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.updateUnProductoResponse> updateUnProductoAsync(e_commerce.siproe.Producto producto) {
            e_commerce.siproe.updateUnProductoRequest inValue = new e_commerce.siproe.updateUnProductoRequest();
            inValue.Body = new e_commerce.siproe.updateUnProductoRequestBody();
            inValue.Body.producto = producto;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).updateUnProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.addProductoResponse e_commerce.siproe.ServicioWebSoap.addProducto(e_commerce.siproe.addProductoRequest request) {
            return base.Channel.addProducto(request);
        }
        
        public void addProducto(e_commerce.siproe.Producto producto) {
            e_commerce.siproe.addProductoRequest inValue = new e_commerce.siproe.addProductoRequest();
            inValue.Body = new e_commerce.siproe.addProductoRequestBody();
            inValue.Body.producto = producto;
            e_commerce.siproe.addProductoResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).addProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.addProductoResponse> e_commerce.siproe.ServicioWebSoap.addProductoAsync(e_commerce.siproe.addProductoRequest request) {
            return base.Channel.addProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.addProductoResponse> addProductoAsync(e_commerce.siproe.Producto producto) {
            e_commerce.siproe.addProductoRequest inValue = new e_commerce.siproe.addProductoRequest();
            inValue.Body = new e_commerce.siproe.addProductoRequestBody();
            inValue.Body.producto = producto;
            return ((e_commerce.siproe.ServicioWebSoap)(this)).addProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_commerce.siproe.getCategoriaResponse e_commerce.siproe.ServicioWebSoap.getCategoria(e_commerce.siproe.getCategoriaRequest request) {
            return base.Channel.getCategoria(request);
        }
        
        public System.Collections.Generic.List<e_commerce.siproe.Categoria> getCategoria() {
            e_commerce.siproe.getCategoriaRequest inValue = new e_commerce.siproe.getCategoriaRequest();
            inValue.Body = new e_commerce.siproe.getCategoriaRequestBody();
            e_commerce.siproe.getCategoriaResponse retVal = ((e_commerce.siproe.ServicioWebSoap)(this)).getCategoria(inValue);
            return retVal.Body.getCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<e_commerce.siproe.getCategoriaResponse> e_commerce.siproe.ServicioWebSoap.getCategoriaAsync(e_commerce.siproe.getCategoriaRequest request) {
            return base.Channel.getCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<e_commerce.siproe.getCategoriaResponse> getCategoriaAsync() {
            e_commerce.siproe.getCategoriaRequest inValue = new e_commerce.siproe.getCategoriaRequest();
            inValue.Body = new e_commerce.siproe.getCategoriaRequestBody();
            return ((e_commerce.siproe.ServicioWebSoap)(this)).getCategoriaAsync(inValue);
        }
    }
}
