//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIII.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comprador", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Comprador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProyectoIII.ServiceReference1.HelloWorldResponse HelloWorld(ProyectoIII.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProyectoIII.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento selectCompradorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectComprador", ReplyAction="*")]
        ProyectoIII.ServiceReference1.selectCompradorResponse selectComprador(ProyectoIII.ServiceReference1.selectCompradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectComprador", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.selectCompradorResponse> selectCompradorAsync(ProyectoIII.ServiceReference1.selectCompradorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento comprador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertComprador", ReplyAction="*")]
        ProyectoIII.ServiceReference1.insertCompradorResponse insertComprador(ProyectoIII.ServiceReference1.insertCompradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertComprador", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.insertCompradorResponse> insertCompradorAsync(ProyectoIII.ServiceReference1.insertCompradorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoIII.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoIII.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectCompradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectComprador", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.selectCompradorRequestBody Body;
        
        public selectCompradorRequest() {
        }
        
        public selectCompradorRequest(ProyectoIII.ServiceReference1.selectCompradorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectCompradorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public selectCompradorRequestBody() {
        }
        
        public selectCompradorRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectCompradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectCompradorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.selectCompradorResponseBody Body;
        
        public selectCompradorResponse() {
        }
        
        public selectCompradorResponse(ProyectoIII.ServiceReference1.selectCompradorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectCompradorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoIII.ServiceReference1.Comprador selectCompradorResult;
        
        public selectCompradorResponseBody() {
        }
        
        public selectCompradorResponseBody(ProyectoIII.ServiceReference1.Comprador selectCompradorResult) {
            this.selectCompradorResult = selectCompradorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCompradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertComprador", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.insertCompradorRequestBody Body;
        
        public insertCompradorRequest() {
        }
        
        public insertCompradorRequest(ProyectoIII.ServiceReference1.insertCompradorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCompradorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoIII.ServiceReference1.Comprador comprador;
        
        public insertCompradorRequestBody() {
        }
        
        public insertCompradorRequestBody(ProyectoIII.ServiceReference1.Comprador comprador) {
            this.comprador = comprador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCompradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCompradorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoIII.ServiceReference1.insertCompradorResponseBody Body;
        
        public insertCompradorResponse() {
        }
        
        public insertCompradorResponse(ProyectoIII.ServiceReference1.insertCompradorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCompradorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertCompradorResult;
        
        public insertCompradorResponseBody() {
        }
        
        public insertCompradorResponseBody(bool insertCompradorResult) {
            this.insertCompradorResult = insertCompradorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ProyectoIII.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ProyectoIII.ServiceReference1.WebService1Soap>, ProyectoIII.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoIII.ServiceReference1.HelloWorldResponse ProyectoIII.ServiceReference1.WebService1Soap.HelloWorld(ProyectoIII.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProyectoIII.ServiceReference1.HelloWorldRequest inValue = new ProyectoIII.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.HelloWorldRequestBody();
            ProyectoIII.ServiceReference1.HelloWorldResponse retVal = ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.HelloWorldResponse> ProyectoIII.ServiceReference1.WebService1Soap.HelloWorldAsync(ProyectoIII.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProyectoIII.ServiceReference1.HelloWorldRequest inValue = new ProyectoIII.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.HelloWorldRequestBody();
            return ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoIII.ServiceReference1.selectCompradorResponse ProyectoIII.ServiceReference1.WebService1Soap.selectComprador(ProyectoIII.ServiceReference1.selectCompradorRequest request) {
            return base.Channel.selectComprador(request);
        }
        
        public ProyectoIII.ServiceReference1.Comprador selectComprador(int id) {
            ProyectoIII.ServiceReference1.selectCompradorRequest inValue = new ProyectoIII.ServiceReference1.selectCompradorRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.selectCompradorRequestBody();
            inValue.Body.id = id;
            ProyectoIII.ServiceReference1.selectCompradorResponse retVal = ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).selectComprador(inValue);
            return retVal.Body.selectCompradorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.selectCompradorResponse> ProyectoIII.ServiceReference1.WebService1Soap.selectCompradorAsync(ProyectoIII.ServiceReference1.selectCompradorRequest request) {
            return base.Channel.selectCompradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.selectCompradorResponse> selectCompradorAsync(int id) {
            ProyectoIII.ServiceReference1.selectCompradorRequest inValue = new ProyectoIII.ServiceReference1.selectCompradorRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.selectCompradorRequestBody();
            inValue.Body.id = id;
            return ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).selectCompradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoIII.ServiceReference1.insertCompradorResponse ProyectoIII.ServiceReference1.WebService1Soap.insertComprador(ProyectoIII.ServiceReference1.insertCompradorRequest request) {
            return base.Channel.insertComprador(request);
        }
        
        public bool insertComprador(ProyectoIII.ServiceReference1.Comprador comprador) {
            ProyectoIII.ServiceReference1.insertCompradorRequest inValue = new ProyectoIII.ServiceReference1.insertCompradorRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.insertCompradorRequestBody();
            inValue.Body.comprador = comprador;
            ProyectoIII.ServiceReference1.insertCompradorResponse retVal = ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).insertComprador(inValue);
            return retVal.Body.insertCompradorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.insertCompradorResponse> ProyectoIII.ServiceReference1.WebService1Soap.insertCompradorAsync(ProyectoIII.ServiceReference1.insertCompradorRequest request) {
            return base.Channel.insertCompradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoIII.ServiceReference1.insertCompradorResponse> insertCompradorAsync(ProyectoIII.ServiceReference1.Comprador comprador) {
            ProyectoIII.ServiceReference1.insertCompradorRequest inValue = new ProyectoIII.ServiceReference1.insertCompradorRequest();
            inValue.Body = new ProyectoIII.ServiceReference1.insertCompradorRequestBody();
            inValue.Body.comprador = comprador;
            return ((ProyectoIII.ServiceReference1.WebService1Soap)(this)).insertCompradorAsync(inValue);
        }
    }
}
